version: "3.9"

services:
  web:
    build: .
    container_name: smart_home_web
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=smartuser
      - MYSQL_PASSWORD=smartpass
      - MYSQL_DATABASE=smarthomedb
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: smart_home_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smarthomedb
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smartpass
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
